### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by jthingelstad** [lionheart/pinboard.py#1]
There appear to be some issues dealing with non-ASCII characters coming back from the Pinboard API. When I do a `pinboard tags` on the command line using my account I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pinboard", line 358, in <module>
    handler.run()
  File "/usr/local/bin/pinboard", line 280, in run
    command_map[self.namespace.subparser]()
  File "/usr/local/bin/pinboard", line 189, in _tags_action
    self._call_api_and_catch_exceptions(self.pinboard.tags.get, handler)
  File "/usr/local/bin/pinboard", line 88, in _call_api_and_catch_exceptions
    value = handler(json_response)
  File "/usr/local/bin/pinboard", line 187, in handler
    print row_format.format(tag, count)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 3: ordinal not in range(128)
```

I believe it is failing on this tag name:

`<tag count="3" tag="Bahá'í" />`

**Comment by dlo** [comment]
Thanks for the report, just fixed!

**Comment by jthingelstad** [comment]
Thanks for fixing this. Note that I’m pretty sure this same bug exists if there is a Unicode character in the description or extended attributes as well.

**Comment by dlo** [comment]
I'll check those out too to be sure.

**Comment by pganson** [comment]
FYI, a few days ago I installed using pip.  I'm having this Unicode issue with the "description" (title) field.  "bookmark = pb.posts.get(...)" works fine but "bookmark.save(...)" fails: 

exception <type 'exceptions.UnicodeEncodeError'>, 'ascii' codec can't encode character u'\u201c' in position 14: ordinal not in range(128)

**Comment by dlo** [comment]
@pganson can you post the description you're trying to save? thanks :)

**Comment by pganson** [comment]
This is stdout from a program I wrote (I retrieved the post by the URL following `line# 1 ***`)

```
----------
line# 1 *** http://lifehacker.com/in-some-jobs-fake-it-til-you-make-it-is-the-right-w-1682636286 *** tag_xyz In Some Jobs, “Fake It ‘til You Make It” Is the Right Way to Go
----------
*** from Pinboard (original) ***
    bookmark: <Bookmark description="tag_xyz In Some Jobs, “Fake It ‘til You Make It” Is the Right Way to Go" url="lifehacker.com">
    tag(s):  [u'_imported', u'_S']
    description:  tag_xyz In Some Jobs, “Fake It ‘til You Make It” Is the Right Way to Go
*** before saving ***
    bookmark: <Bookmark description="In Some Jobs, “Fake It ‘til You Make It” Is the Right Way to Go" url="lifehacker.com">
    tag(s):  [u'_imported', u'_S', u'_batch', u'tag_xyz']
    description:  In Some Jobs, “Fake It ‘til You Make It” Is the Right Way to Go
ERROR - save to Pinboard failed - exception <type 'exceptions.UnicodeEncodeError'>, 'ascii' codec can't encode character u'\u201c' in position 14: ordinal not in range(128)
```

**Comment by dlo** [comment]
Looks like it's those angled quotes. Thanks @pganson. I'll throw up a fix in a couple hours. :)

**Comment by pganson** [comment]
If you're going to translate specific characters (this1 --> that1, this2 --> that2, ...), let me know.  I did not post all of the unicode errors that I received, just a sample one.

**Comment by dlo** [comment]
Nope, not planning on translating specific characters. Just going to re-encode the data so it can handle anything that's thrown at it.

**Comment by dlo** [comment]
@pganson please re-update from PyPi and LMK if everything's working as expected. Thanks!

**Comment by pganson** [comment]
early results --> looks good

**Comment by pganson** [comment]
I finished processing and the results look good.  Thanks for the fast solution and the great project - it's made my conversion from Google bookmarks to Pinboard much easier.

I'm looking into another issue with my Python program, failing to retrieve some URLs.  The URL stored on Pinboard looks like:

```
http://www.raspberrypi.org/forums/viewtopic.php?f=66&t=49928&start=525
```

but after I download all posts to my system, it looks like:

```
http://www.raspberrypi.org/forums/viewtopic.php?f=66&amp;t=49928&amp;start=525
```

If I manually change all of the `&amp;` to `&`, it runs fine.

**Comment by dlo** [comment]
@pganson great! I'm going to close this issue. Could you open another one about the weird ampersand behavior?
