### ISSUE TITLE
Utf-8

### ISSUE THREAD

**Issue by infontology** [lionheart/pinboard.py#13]
Excellent module -- thanks!

I ran into an exception in Python 3. File pinboard.py line 166

value = map(lambda k: k.decode("utf8"), kwargs[field])

Had to remove 

---
.decode("utf8")
---

for it to run.

**Comment by jaanus** [comment]
+1. Also ran into this and fixed it the same way.

**Comment by marcw** [comment]
same here.

**Comment by dlo** [comment]
Fixed by #15. New PyPi release coming out shortly.
