### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by alessandro-molari** [lionheart/pinboard.py#5]
Hi,

I'd like to know if this project is already maintained.

Thanks :+1:

**Comment by dlo** [comment]
Hey @alem0lars, yup, this project is maintained. The Pinboard API hasn't changed in years and there aren't any bugs with the library, hence the lack of activity. Is there anything you'd like to contribute?

**Comment by alessandro-molari** [comment]
Ah ok.

Nice :)

I was going to choose a commandline pinboard client and I wanted to be sure I was going for a maintained client.

Thanks for the immediate response :+1: 

---

_PS: Probably one missing feature is the zsh commandline completion._

**Comment by alessandro-molari** [comment]
Ah, btw, is it possible to release a version so I can use it instead of the origin branch head in my ebuild?

Thanks

**Comment by dlo** [comment]
@alem0lars if you wanted to add zsh completion in a PR I would gladly accept :)

**Comment by dlo** [comment]
Just pushed up 1.0.0 to PyPi. Might take a few minutes to propagate.

**Comment by alessandro-molari** [comment]
Thanks

**Comment by alessandro-molari** [comment]
Is it compatible with python3 ?

I'm getting the following error using python 3.4:

```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from pinboard import metadata
  File "/var/tmp/portage/app-misc/pinboard-1.0.0/work/pinboard.py-1.0.0/pinboard/__init__.py", line 1, in <module>
    from .pinboard import Pinboard
  File "/var/tmp/portage/app-misc/pinboard-1.0.0/work/pinboard.py-1.0.0/pinboard/pinboard.py", line 5, in <module>
    import urllib2
ImportError: No module named 'urllib2'
```

**Comment by dlo** [comment]
Nope, it's not Python 3 compatible, though since it has no dependencies adding support would be simple if you'd like to take this on.
