### ISSUE TITLE
bin/pinboard broken for python3

### ISSUE THREAD

**Issue by jmcantrell** [lionheart/pinboard.py#7]
There seems to be some problems when using the command line interface when installed in python3.
The first encountered was using `raw_input` instead of `input` when doing `pinboard login`.

Just wanted to see if you were aware of this, and if you're open to a pull request, before getting too deep into it.

**Comment by johnharris85** [comment]
I'm just working on a PR for something else and hit this, unfortunately it's broken both ways. In 2 the `import configparser` fails (was renamed from `ConfigParser`) but in 3 `raw_input` fails. 

@dlo do you have a preference for the cli to support 2, 3 or both (via six or something)? Then I will tailor / submit my PRs.

**Comment by dlo** [comment]
@johnharris85 3 only would be perfect. Thanks!

**Comment by dlo** [comment]
I think this has been fixed.
